package main

import (
	"fmt"
	"image/png"
	"os"

	"github.com/boombuler/barcode"
	"github.com/boombuler/barcode/qr"
)

//RUN ON THE TERMINAL
//go build datamatrix.go && ./datamatrix

func main() {

	//LIMITADO A QUASE 200 ITEMS NO ARRAY
	skus := []string{
		"ACUC-A-AMARELO-SID-10X1KG",
		"ACUC-B-DCG-SID-10X1KG",
		"ACUC-ICING-SID-1X10KG",
		"ACUC-B-SACOS-GR-SID-1X25KG",
		"ACUC-G-SACOS-SID-1X25KG",
		"ACUC-B-1200-DOS-SID-1X96KG",
		"AZEI-SA-1X5LT",
		"AZEI-SA-1X1LT",
		"OLEO-A-GIRASSOL-ABR-1X5LT",
		"GORD-V-FRIT-ABR-1X10LT",
		"OLEO-ALIMENTA-FUL-1X1LT",
		"AZEI-B-DE-AZEIT-COO-1X5LT",
		"OLEO-A-TEMPERO-GDO-1X5LT",
		"VINA-UNI-1X075LT",
		"VINA-D-MESA-SA-1X12LT",
		"AZEI-D-MESA-SA-1X12LT",
		"BOLA-TOSTADA-CUE-1X08KG",
		"BOLA-MARIA-UNI-1X08KG",
		"CAFE-D-MMP-DEL-1X025KG",
		"CEVA-SOLUVEL-NES-1X12KG",
		"CHA-D-CIDREIRA-LIP-6X25UN",
		"CHA-D-CAMOMILA-LIP-6X25UN",
		"CHA-D-TILIA-LIP-6X25UN",
		"CHA-D-LUCIA-LI-LIP-6X25UN",
		"CHA-G-TEA-ORIE-LIP-6X25UN",
		"CHA-G-TEA-CLAS-LIP-6X25UN",
		"CHA-P-YELLOW-L-LIP-6X25UN",
		"CHA-F-VERMELHO-LIP-6X25UN",
		"CHA-M-E-CANELA-LIP-6X25UN",
		"CHA-TILIA-VIV-12X25UN",
		"CHA-D-CIDREIRA-VIV-12X25UN",
		"CHA-D-CAMOMILA-VIV-12X25UN",
		"CHA-D-LUCIA-LI-VIV-12X25UN",
		"CHOC-C-44%-CACA-NES-1X200KG",
		"CHOC-B-MESTRE-P-MAS-1X3KG",
		"CREM-D-CMP-MAS-1X5KG",
		"LATA-D-PESSEGO-UNI-3X265KG",
		"LATA-D-PESSEGO-UNI-12X084KG",
		"LATA-D-ANANAS-CIM-6X3KG",
		"LATA-D-ANANAS-UNI-12X082KG",
		"LATA-D-COGUMELO-UNI-3X25KG",
		"LATA-D-COGUMELO-UNI-12X0780KG",
		"LATA-D-COGUMELO-UNI-12X0780KG-1",
		"LATA-D-FEIJAO-M-PIC-3X25KG",
		"LATA-D-FMC-UNI-12X780KG",
		"LATA-D-FEIJAO-B-PIC-3X25KG",
		"LATA-D-PIMENTOS-CIM-12X0780KG",
		"LATA-D-FBC-UNI-12X0780KG",
		"LATA-D-GRAO-UNI-3X25KG",
		"LATA-D-GRAO-UNI-12X0780KG",
		"LATA-D-FFC-UNI-12X0780KG",
		"LATA-D-FVC-UNI-12X0780KG",
		"SACO-D-FBS-PL-1X5KG",
		"SACO-D-FCS-PL-1X5KG",
		"SACO-D-GRAO-SEC-PL-1X5KG",
		"SACO-D-FFS-PL-1X5KG",
		"LATA-D-AEP-UNI-1X173KG",
		"LATA-D-AEP-UNI-1X011KG",
		"LATA-D-SET-UNI-1X25KG",
		"LATA-D-SEO-JUP-1X25KG",
		"LATA-D-FDC-JUP-1X25KG",
		"LATA-D-CAVALINH-JUP-1X25KG",
		"LATA-D-CARAPAUS-JUP-1X25KG",
		"LATA-D-TOMATE-UNI-12X0780KG",
		"LATA-D-TOMATE-UNI-6X255KG",
		"LATA-D-TOMATE-P-KNO-1X6KG",
		"LATA-D-TOMATE-C-CIR-1X6KG",
		"LATA-D-PTT-KNO-1X6KG",
		"LATA-D-CUBOS-TO-KNO-1X6KG",
		"CREM-D-TOMATE-KNO-1X6KG",
		"FRAS-D-FMC-UNI-1X057KG",
		"FRAS-D-FBC-UNI-1X057KG",
	}

	//os.RemoveAll("images/")
	//os.MkdirAll("images/", os.ModePerm)

	for index, element := range skus {

		fmt.Printf("%d Data Matrix Created: %s.png\n", index, element)
		// Create the barcode
		qrCode, _ := qr.Encode(element, qr.M, qr.Auto)
		// Scale the barcode to 800x800 pixels
		qrCode, _ = barcode.Scale(qrCode, 800, 800)
		// create the output file
		file, _ := os.Create("images/" + element + ".png")
		defer file.Close()
		// encode the barcode as png
		png.Encode(file, qrCode)
	}
}
